### ISSUE TITLE
 "Region is missing"

### ISSUE THREAD

**Issue by ericksposito** [awslabs/aws-codeservices-plugins-for-backstage#53]
Hello, I'm trying to implement the plugin in the company I work for. But after having configured everything, when trying to access the page where the codepipeline widget should appear, I get an error 500.

![region_missing](https://user-images.githubusercontent.com/9743951/216435021-82f70a2f-5f86-4a70-a1a0-c9e21289c68a.png)
in the print you can see that he is trying to access the arn.
below the backend code and in the app-config
awsCOdeSuite.ts
```
import { createRouter } from "@aws/aws-codesuite-backend-plugin-for-backstage";
import { PluginEnvironment } from "../types";

export default async function createPlugin(env: PluginEnvironment) {
  return await createRouter({
    logger: env.logger,
    config: env.config,
  });
}
```
app-config.yaml
```
app:
  title: Portal do Desenvolvedor
  baseUrl: http://localhost:3000


aws:
  mainAccount:
    accessKeyId: xxxxxxxxxxxxxxxxxxxx
    secretAccessKey: xxxxxxxxxxxxxxxx
    region: 'us-east-2'
```
Can someone help me?
